name: Only manual approval
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          approvers: Trimukesh,skrafiq
          secret: ${{ secrets.TOKEN }}
          minimum-approvals: 1 
          
      - name: Run the script
        run: echo hello world
